onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb/clk
add wave -noupdate /tb/res
add wave -noupdate /tb/pif/clk
add wave -noupdate /tb/pif/res
add wave -noupdate /tb/pif/wr_rd
add wave -noupdate /tb/pif/addr
add wave -noupdate /tb/pif/wdata
add wave -noupdate /tb/pif/rdata
add wave -noupdate /tb/pif/valid
add wave -noupdate /tb/pif/ready
add wave -noupdate /tb/pif/dri_cb/wr_rd
add wave -noupdate /tb/pif/dri_cb/addr
add wave -noupdate /tb/pif/dri_cb/wdata
add wave -noupdate /tb/pif/dri_cb/valid
add wave -noupdate /tb/pif/dri_cb/rdata
add wave -noupdate /tb/pif/dri_cb/ready
add wave -noupdate /tb/pif/dri_cb/dri_cb_event
add wave -noupdate /tb/pif/mon_cb/wr_rd
add wave -noupdate /tb/pif/mon_cb/addr
add wave -noupdate /tb/pif/mon_cb/wdata
add wave -noupdate /tb/pif/mon_cb/rdata
add wave -noupdate /tb/pif/mon_cb/valid
add wave -noupdate /tb/pif/mon_cb/ready
add wave -noupdate /tb/pif/mon_cb/mon_cb_event
add wave -noupdate /tb/dut/clk
add wave -noupdate /tb/dut/res
add wave -noupdate /tb/dut/wr_rd
add wave -noupdate /tb/dut/valid
add wave -noupdate /tb/dut/wdata
add wave -noupdate /tb/dut/addr
add wave -noupdate /tb/dut/rdata
add wave -noupdate /tb/dut/ready
add wave -noupdate /tb/dut/i
add wave -noupdate /tb/dut/m_assr/clk
add wave -noupdate /tb/dut/m_assr/res
add wave -noupdate /tb/dut/m_assr/wr_rd
add wave -noupdate /tb/dut/m_assr/valid
add wave -noupdate /tb/dut/m_assr/wdata
add wave -noupdate /tb/dut/m_assr/addr
add wave -noupdate /tb/dut/m_assr/rdata
add wave -noupdate /tb/dut/m_assr/ready
add wave -noupdate /uvm_pkg::uvm_component_name_check_visitor::visit/immed__262
add wave -noupdate /tb/dut/m_assr/assert__write
add wave -noupdate /tb/dut/m_assr/assert__ready_r
add wave -noupdate /tb/clk
add wave -noupdate /tb/res
add wave -noupdate /tb/pif/clk
add wave -noupdate /tb/pif/res
add wave -noupdate /tb/pif/wr_rd
add wave -noupdate /tb/pif/addr
add wave -noupdate /tb/pif/wdata
add wave -noupdate /tb/pif/rdata
add wave -noupdate /tb/pif/valid
add wave -noupdate /tb/pif/ready
add wave -noupdate /tb/pif/dri_cb/wr_rd
add wave -noupdate /tb/pif/dri_cb/addr
add wave -noupdate /tb/pif/dri_cb/wdata
add wave -noupdate /tb/pif/dri_cb/valid
add wave -noupdate /tb/pif/dri_cb/rdata
add wave -noupdate /tb/pif/dri_cb/ready
add wave -noupdate /tb/pif/dri_cb/dri_cb_event
add wave -noupdate /tb/pif/mon_cb/wr_rd
add wave -noupdate /tb/pif/mon_cb/addr
add wave -noupdate /tb/pif/mon_cb/wdata
add wave -noupdate /tb/pif/mon_cb/rdata
add wave -noupdate /tb/pif/mon_cb/valid
add wave -noupdate /tb/pif/mon_cb/ready
add wave -noupdate /tb/pif/mon_cb/mon_cb_event
add wave -noupdate /tb/dut/clk
add wave -noupdate /tb/dut/res
add wave -noupdate /tb/dut/wr_rd
add wave -noupdate /tb/dut/valid
add wave -noupdate /tb/dut/wdata
add wave -noupdate /tb/dut/addr
add wave -noupdate /tb/dut/rdata
add wave -noupdate /tb/dut/ready
add wave -noupdate /tb/dut/i
add wave -noupdate /tb/dut/m_assr/clk
add wave -noupdate /tb/dut/m_assr/res
add wave -noupdate /tb/dut/m_assr/wr_rd
add wave -noupdate /tb/dut/m_assr/valid
add wave -noupdate /tb/dut/m_assr/wdata
add wave -noupdate /tb/dut/m_assr/addr
add wave -noupdate /tb/dut/m_assr/rdata
add wave -noupdate /tb/dut/m_assr/ready
add wave -noupdate /uvm_pkg::uvm_component_name_check_visitor::visit/immed__262
add wave -noupdate /tb/dut/m_assr/assert__write
add wave -noupdate /tb/dut/m_assr/assert__ready_r
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {445 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ns} {1 us}
